%YAML:1.0
# config for fw_zed2i_f9p

#topic parameters
imu_topic: "/imu/data_raw"
cam_left_topic: "/stereo/left/image_raw"
cam_right_topic: "/stereo/right/image_raw"

# intrinsic
model_type: PINHOLE
camera_name: cam0
image_width: 1280
image_height: 560
distortion_parameters:
   k1: -0.01908
   k2: 0.04321
   p1: 0.00159
   p2: 0.00048
projection_parameters:
   fx: 814.726
   fy: 810.614
   cx: 616.681
   cy: 274.980
   
# extrinsic
extrinsicRotation: !!opencv-matrix        # R^{imu}_{cam}
   rows: 3
   cols: 3
   dt: d
   data: [-0.00681,-0.01532,0.99987, 
          -0.99998,0.00033,-0.00680, 
         -0.00023,-0.99988,-0.01532]
extrinsicTranslation: !!opencv-matrix     # t^{imu}_{cam}
   rows: 3
   cols: 1
   dt: d
   data: [1.71239, 0.24740, -0.11589]

# tracker config
max_cnt: 200            # max feature number in feature tracking
min_dist: 40              # min distance between two features 
freq: 0                         # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be the same as raw image 
show_track: 1          # publish tracking image as topic
show_timer: 0       # show time counting
timer_warning_thres: 50.0 # in (ms)
equalize: 1                # if image is too dark or light, turn on equalize to find enough features
window_size: 20
epipolar_thres: 15.0
F_threshold: 1.0
print_track_info: 1
